import { supabase } from './supabase'
import type { MentorLesson, MentorProgress } from './types'
import { updateMissionProgress } from './missionStore'

const KEY='alphatekx_mentor_progress'; const EVENT='alphatekx:mentor-change'
const read=():MentorProgress[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
const write=(values:MentorProgress[])=>{localStorage.setItem(KEY,JSON.stringify(values));window.dispatchEvent(new Event(EVENT))}
const subjectFrom=(goal:string)=>goal.replace(/^.*?\blearn\s+/i,'').replace(/\b(course|from scratch|today)\b/gi,'').trim()||'the subject'
function curriculum(subject:string):MentorLesson[]{const topics=['Foundations','Core concepts','Guided practice','Real-world application','Mastery challenge'];return topics.map((topic,index)=>({id:`lesson-${index+1}`,title:`${index+1}. ${topic}`,objective:`Understand and apply ${topic.toLowerCase()} in ${subject}.`,explanation:`This lesson builds ${subject} step by step. Start with the mental model, inspect a worked example, then explain the idea in your own words before continuing.`,codeExample:index===0?`// ${subject} foundation\nconst practice = "learn by building";`:`// ${topic}\nfunction applyConcept(input) { return input; }`,quiz:{question:`Which action best demonstrates ${topic.toLowerCase()}?`,options:['Memorizing without practice','Applying the concept to a new problem','Skipping examples','Avoiding feedback'],answer:1}}))}
export function isMentorMission(goal:string){return /\b(learn|teach|course|study)\b/i.test(goal)}
export function getMentorProgress(missionId:string){return read().find(item=>item.missionId===missionId)??null}
export function ensureMentorProgress(missionId:string,goal:string){const current=getMentorProgress(missionId);if(current)return current;const subject=subjectFrom(goal);const next={missionId,subject,lessons:curriculum(subject),lessonsCompleted:[],quizScores:{}};write([next,...read()]);void saveCloud(next);return next}
export function completeLesson(missionId:string,lessonId:string,score:number){const values=read().map(item=>item.missionId===missionId?{...item,lessonsCompleted:Array.from(new Set([...item.lessonsCompleted,lessonId])),quizScores:{...item.quizScores,[lessonId]:score}}:item);write(values);const next=values.find(item=>item.missionId===missionId);if(next){updateMissionProgress(missionId,Math.round(next.lessonsCompleted.length/Math.max(1,next.lessons.length)*100));void saveCloud(next)}return next??null}
export function subscribeMentor(listener:()=>void){window.addEventListener(EVENT,listener);return()=>window.removeEventListener(EVENT,listener)}
export async function hydrateMentor(missionId:string){if(!supabase)return;const{data}=await supabase.from('mentor_progress').select('mission_id,subject,lessons,lessons_completed,quiz_scores').eq('mission_id',missionId).maybeSingle();if(!data)return;const next:MentorProgress={missionId:data.mission_id,subject:data.subject,lessons:data.lessons,lessonsCompleted:data.lessons_completed,quizScores:data.quiz_scores};write([next,...read().filter(item=>item.missionId!==missionId)])}
async function saveCloud(progress:MentorProgress){if(!supabase)return;const{data}=await supabase.auth.getUser();if(!data.user)return;await supabase.from('mentor_progress').upsert({mission_id:progress.missionId,user_id:data.user.id,subject:progress.subject,lessons:progress.lessons,lessons_completed:progress.lessonsCompleted,quiz_scores:progress.quizScores})}
