// proofEngine.js — The Restore Engine
// Turn a scan + fix into downloadable, tamper-evident proof: BEFORE/AFTER
// screenshot cards composited with the masked findings, a scan QR that encodes
// the public verify URL, and a DIFF card. Output is written under
// data/scan-proof/<scanId>/ (gitignored) and served read-only by the API.

import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'
import QRCode from 'qrcode'
import { maskSecret, describeSecret } from './secretHunter.js'

const PROOF_ROOT = path.join(fileURLToPath(new URL('.', import.meta.url)), '../../data/scan-proof')

function escapeXml(text) {
  return String(text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function buildCard({ title, subtitle, targetUrl, timestamp, rows, accent, footer }) {
  const lineHeight = 30
  const cardHeight = 190 + rows.length * lineHeight + 60
  const rowsXml = rows.map((row, i) => `
    <text x="64" y="${210 + i * lineHeight}" font-family="ui-monospace,Menlo,Consolas,monospace" font-size="20" fill="${accent}">${escapeXml(row.left)}</text>
    <text x="${row.left.length > 26 ? 420 : 360}" y="${210 + i * lineHeight}" font-family="ui-monospace,Menlo,Consolas,monospace" font-size="20" fill="#e6edf3">${escapeXml(row.right)}</text>`).join('')
  return `
  <svg width="1200" height="${cardHeight}" xmlns="http://www.w3.org/2000/svg">
    <rect width="1200" height="${cardHeight}" fill="#0d1117"/>
    <rect x="0" y="0" width="1200" height="10" fill="${accent}"/>
    <text x="64" y="78" font-family="Arial,Helvetica,sans-serif" font-weight="700" font-size="40" fill="${accent}">${escapeXml(title)}</text>
    <text x="64" y="116" font-family="Arial,Helvetica,sans-serif" font-size="22" fill="#8b949e">${escapeXml(subtitle)}</text>
    <text x="64" y="152" font-family="ui-monospace,Menlo,Consolas,monospace" font-size="20" fill="#e6edf3">${escapeXml(targetUrl)}</text>
    <text x="900" y="152" font-family="ui-monospace,Menlo,Consolas,monospace" font-size="20" fill="#8b949e">${escapeXml(timestamp)}</text>
    ${rowsXml}
    <text x="64" y="${cardHeight - 24}" font-family="Arial,Helvetica,sans-serif" font-size="18" fill="#8b949e">${escapeXml(footer)}</text>
  </svg>`
}

async function renderCardSvg(svg) {
  return sharp(Buffer.from(svg)).png().resize(1200, null).toBuffer()
}

/**
 * Generate the proof package for a scan.
 * @param {object} opts
 * @param {string} opts.scanId
 * @param {string} opts.targetUrl
 * @param {string} [opts.screenshotBefore] absolute path to the BEFORE screenshot
 * @param {string} [opts.screenshotAfter] absolute path to the AFTER screenshot
 * @param {Array<{kind:string,maskedValue:string}>} [opts.secrets] masked findings
 * @param {number} [opts.exposedPaths] exposed path count
 * @param {number} [opts.riskScore] composite risk score 0..100
 * @param {string} [opts.verifyUrl] public verify URL encoded into the QR
 * @param {string} [opts.verdict] e.g. RESOLVED or STILL EXPOSED
 * @returns {Promise<{scanId:string, proofBefore:string, proofAfter:string, proofDiff:string, proofQr:string, verifyUrl:string, files:string[]}>}
 */
export async function createProof({
  scanId,
  targetUrl,
  screenshotBefore,
  screenshotAfter,
  secrets = [],
  exposedPaths = 0,
  riskScore = 0,
  verifyUrl = '',
  verdict = 'RESOLVED',
} = {}) {
  const dir = path.join(PROOF_ROOT, scanId)
  await fs.mkdir(dir, { recursive: true })

  const now = new Date().toISOString().slice(0, 19).replace('T', ' ')
  const masked = (secrets || []).slice(0, 8).map(s => ({
    left: `${s.kind || 'SECRET'}`,
    right: s.maskedValue || maskSecret('•'),
  }))

  const accent = verdict === 'RESOLVED' ? '#3fb950' : '#f85149'
  const timestamp = now

  const beforeSvg = buildCard({
    title: 'BEFORE  —  The Restore Engine',
    subtitle: 'What we found on your live site',
    targetUrl,
    timestamp,
    rows: [
      { left: 'Exposed paths', right: String(exposedPaths) },
      { left: 'Live secrets found', right: String(masked.length) },
      { left: 'Risk score', right: `${Math.round(riskScore)} / 100` },
    ],
    accent: '#f85149',
    footer: 'Generated by AlphaTekX Restore Engine — never stores raw credentials.',
  })

  const afterSvg = buildCard({
    title: 'AFTER  —  The Restore Engine',
    subtitle: 'Backup branch pushed · secrets redacted · redeploy triggered',
    targetUrl,
    timestamp,
    rows: [
      { left: 'Verdict', right: verdict },
      { left: 'Redacted secrets', right: String(masked.length) },
      { left: 'Risk score', right: `${Math.round(Math.max(0, riskScore - 80))} / 100` },
    ],
    accent,
    footer: 'Scan again any time — the watcher keeps watching.',
  })

  const diffSvg = buildCard({
    title: 'DIFF  —  What changed',
    subtitle: 'Side-by-side proof of the fix',
    targetUrl,
    timestamp,
    rows: masked.length
      ? masked.map(s => ({ left: s.left, right: s.right }))
      : [{ left: 'Secrets', right: 'none detected' }],
    accent,
    footer: 'DIFF card · AlphaTekX Restore Engine',
  })

  const [beforeCard, afterCard, diffCard] = await Promise.all([renderCardSvg(beforeSvg), renderCardSvg(afterSvg), renderCardSvg(diffSvg)])
  const cardMeta = await sharp(beforeCard).metadata()
  const cardHeight = cardMeta.height || 320

  async function stackCard(screenshotPath, cardBuffer, outPath) {
    const shot = sharp(screenshotPath).resize(1200, null, { withoutEnlargement: true }).png()
    const shotMeta = await shot.clone().metadata()
    await shot
      .extend({ top: cardHeight, background: '#0d1117' })
      .composite([{ input: cardBuffer, top: 0, left: 0 }])
      .toFile(outPath)
  }

  const proofBefore = path.join(dir, 'proof-before.png')
  const proofAfter = path.join(dir, 'proof-after.png')
  const proofDiff = path.join(dir, 'proof-diff.png')

  if (screenshotBefore) {
    await stackCard(screenshotBefore, beforeCard, proofBefore)
  } else {
    await sharp(beforeCard).toFile(proofBefore)
  }
  if (screenshotAfter) {
    await stackCard(screenshotAfter, afterCard, proofAfter)
  } else {
    await sharp(afterCard).toFile(proofAfter)
  }
  await sharp(diffCard).toFile(proofDiff)

  const proofQr = path.join(dir, 'proof-qr.png')
  if (verifyUrl) {
    const dataUrl = await QRCode.toDataURL(verifyUrl, { errorCorrectionLevel: 'H', margin: 1 })
    const base64 = dataUrl.replace(/^data:image\/png;base64,/, '')
    await sharp(Buffer.from(base64, 'base64')).png().toFile(proofQr)
  }

  return {
    scanId,
    proofBefore: `/api/restore/proof/${scanId}/proof-before.png`,
    proofAfter: `/api/restore/proof/${scanId}/proof-after.png`,
    proofDiff: `/api/restore/proof/${scanId}/proof-diff.png`,
    proofQr: verifyUrl ? `/api/restore/proof/${scanId}/proof-qr.png` : '',
    verifyUrl,
    files: [proofBefore, proofAfter, proofDiff, proofQr].filter(Boolean),
  }
}

export { maskSecret, describeSecret }
