import { useEffect, useMemo, useState } from 'react'
import { Search, Star, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../lib/auth'
import { getMarketplaceItems, hydrateMarketplaceStore, hydrateMissionStore, subscribeStore } from '../lib/missionStore'
import { getReviews, hydrateReviews, saveReview, subscribeReviews } from '../lib/reviewStore'
import type { MarketplaceItem, MarketplaceReview } from '../lib/types'

const categories = ['All', 'Websites', 'Apps', 'Workers', 'Templates']
const categoryMatches = (selected: string, actual: string) => selected === 'All' || selected === actual || (selected === 'Apps' && ['Web Apps','Mobile','Extensions','API','SaaS'].includes(actual)) || (selected === 'Templates' && ['Templates','UI Kits'].includes(actual))

export default function Marketplace() {
  const [items, setItems] = useState(getMarketplaceItems())
  const [category, setCategory] = useState('All')
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')
  const [loading, setLoading] = useState(true)
  const [buying, setBuying] = useState('')
  const [selected, setSelected] = useState<MarketplaceItem | null>(null)
  const [reviews, setReviews] = useState<MarketplaceReview[]>(getReviews())
  const [rating, setRating] = useState(5)
  const [comment, setComment] = useState('')
  const { user } = useAuth()
  useEffect(() => subscribeStore(() => setItems(getMarketplaceItems())), [])
  useEffect(() => subscribeReviews(() => setReviews(getReviews())), [])
  useEffect(() => { hydrateMarketplaceStore().finally(() => setLoading(false)); void hydrateReviews() }, [])
  const visible = useMemo(() => items.filter(item => categoryMatches(category, item.category) && (item.title.toLowerCase().includes(query.toLowerCase()) || item.description.toLowerCase().includes(query.toLowerCase()))), [items, category, query])
  const itemReviews = (id: string) => reviews.filter(review => review.itemId === id)
  const acquire = async (item: MarketplaceItem) => { setBuying(item.id); setNotice(item.priceType === 'paid' ? 'Opening secure checkout...' : 'Adding creation...'); try { const payments = await import('../lib/paystack'); if (item.priceType === 'paid') await payments.purchaseMarketplaceItem(item.id, user?.email ?? '', item.price); else await payments.acquireFreeMarketplaceItem(item.id); await Promise.all([hydrateMarketplaceStore(), hydrateMissionStore()]); setNotice('Added to your creations.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Purchase failed') } finally { setBuying('') } }
  const submitReview = async () => { if (!user || !selected || comment.trim().length < 2) return; try { await saveReview(selected.id, user.id, rating, comment); setComment(''); setNotice('Review published.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Review failed') } }

  return <div className="min-h-screen px-5 py-8 md:px-10"><div className="mx-auto max-w-6xl"><h1 className="text-xl font-semibold md:text-2xl">Marketplace</h1><p className="mt-2 text-sm text-white/55">Find useful apps, websites, helpers, and templates.</p>{notice && <div className="mt-5 rounded-lg border border-white/[.12] liquid-glass px-4 py-3 text-sm">{notice}</div>}
    <div className="mt-6 flex flex-col gap-3"><label className="flex min-h-12 items-center gap-3 rounded-xl border border-white/[.12] liquid-glass px-4 shadow-sm"><Search size={16} className="text-white/45"/><input value={query} onChange={event => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search marketplace"/></label><div className="flex gap-2 overflow-x-auto">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`min-h-10 shrink-0 rounded-full px-4 text-sm ${category === item ? 'btn-alpha text-white' : 'border border-white/[.15] liquid-glass text-white/80'}`} type="button">{item}</button>)}</div></div>
    {loading ? <div className="mt-8 grid animate-pulse gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(item => <div key={item} className="h-64 rounded-xl bg-white/[.12]"/>)}</div> : visible.length ? <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(item => { const reviewCount = itemReviews(item.id).length; return <article key={item.id} className="rounded-xl border border-white/[.12] liquid-glass p-5 shadow-sm transition-colors hover:border-[#E56B2D]"><button onClick={() => setSelected(item)} className="grid aspect-[16/9] w-full place-items-center rounded-lg border border-white/[.12] bg-white/[.04]" type="button"><span className="text-xs font-medium uppercase tracking-wider text-white/45">{item.category}</span></button><div className="mt-5 flex items-start justify-between gap-3"><div className="min-w-0"><button onClick={() => setSelected(item)} className="block truncate text-left text-base font-semibold" type="button">{item.title}</button><Link to={`/creator/${item.ownerId ?? item.id}`} className="mt-1 block text-sm text-white/55">by {item.creator}</Link></div><strong className="shrink-0 text-sm">{item.priceType === 'free' ? 'Free' : `NGN ${item.price.toLocaleString()}`}</strong></div>{reviewCount > 0 && <p className="mt-3 text-xs text-white/55"><Star size={13} className="mr-1 inline fill-[#E56B2D]"/>{(itemReviews(item.id).reduce((sum, review) => sum + review.rating, 0) / reviewCount).toFixed(1)} ({reviewCount})</p>}<button disabled={buying === item.id} onClick={() => void acquire(item)} className="mt-5 min-h-11 w-full rounded-lg btn-alpha text-sm font-medium text-white disabled:opacity-50" type="button">{buying === item.id ? 'Processing...' : item.priceType === 'paid' ? 'Buy' : 'Add to creations'}</button></article>})}</div> : <Empty/>}
  </div>{selected && <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4" onMouseDown={() => setSelected(null)}><section className="mx-auto my-6 w-full max-w-2xl rounded-xl border border-white/[.12] liquid-glass p-6 shadow-sm" onMouseDown={event => event.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="text-sm text-white/55">{selected.category}</p><h2 className="mt-1 text-xl font-semibold">{selected.title}</h2></div><button onClick={() => setSelected(null)} className="grid size-11 place-items-center rounded-lg hover:bg-white/[.04]" aria-label="Close"><X size={18}/></button></div><div className="mt-5 aspect-video rounded-lg border border-white/[.12] bg-white/[.04]"/><p className="mt-5 text-sm leading-6 text-white/70">{selected.description}</p><div className="mt-5 flex items-center justify-between border-t border-white/[.12] pt-5"><Link to={`/creator/${selected.ownerId ?? selected.id}`} className="text-sm underline">View {selected.creator}'s profile</Link><strong>{selected.priceType === 'free' ? 'Free' : `NGN ${selected.price.toLocaleString()}`}</strong></div><h3 className="mt-8 text-sm font-semibold">Reviews</h3><div className="mt-3 space-y-3">{itemReviews(selected.id).map(review => <div key={review.id} className="rounded-lg border border-white/[.12] p-4"><span className="text-sm">{'★'.repeat(review.rating)}</span><p className="mt-2 text-sm text-white/70">{review.comment}</p></div>)}{!itemReviews(selected.id).length && <p className="text-sm text-white/55">No reviews yet.</p>}</div><div className="mt-6 rounded-lg border border-white/[.12] p-4"><p className="text-sm font-semibold">Leave a review</p><div className="mt-3 flex gap-1">{[1,2,3,4,5].map(value => <button key={value} onClick={() => setRating(value)} className={`text-xl ${value <= rating ? 'text-white' : 'text-white/35'}`} type="button">★</button>)}</div><textarea value={comment} onChange={event => setComment(event.target.value)} className="mt-3 h-24 w-full rounded-lg border border-white/[.15] p-3 text-sm outline-none" placeholder="Share useful feedback"/><button onClick={() => void submitReview()} disabled={comment.trim().length < 2} className="mt-3 min-h-10 rounded-lg btn-alpha px-4 text-sm font-medium text-white disabled:opacity-40" type="button">Publish review</button></div></section></div>}</div>
}
function Empty() { return <div className="mt-8 grid min-h-64 place-items-center rounded-xl border border-dashed border-white/[.15] liquid-glass text-center"><div><h2 className="text-base font-semibold">Nothing here yet</h2><p className="mt-2 text-sm text-white/55">Published creations will appear here.</p></div></div> }
