"use client"

import { type ReactNode } from "react"
import {
  ArrowRight,
  CheckCircle2,
  ChevronRight,
  FileText,
  GitBranch,
  Lock,
  Mail,
  PanelsTopLeft,
  ShieldCheck,
  Sparkles,
  Table2,
  Workflow,
} from "lucide-react"

const pillars = [
  {
    title: "Voice that sounds like you",
    body: "Your AI learns from real documents, emails, notes, and product history so every post feels authored by you, not generated by generic software.",
  },
  {
    title: "One operating layer",
    body: "LinkedIn, Gmail, Discord, GitHub, Google Docs, and Sheets all work together instead of competing for your attention.",
  },
  {
    title: "Approval stays human",
    body: "You keep control over what goes out. The system handles the repetitive work so you stay focused on judgment and strategy.",
  },
]

const steps = [
  {
    title: "1. Learn your world",
    body: "We read your work, your messages, and your product context so the voice model becomes an extension of your leadership.",
  },
  {
    title: "2. Create your month",
    body: "The engine drafts posts, replies, and content directions in one motion instead of making you start from zero every time.",
  },
  {
    title: "3. Publish without friction",
    body: "You approve with one click and AlphaTekX executes across the channels that matter while you stay in flow.",
  },
]

const platforms = [
  { name: "LinkedIn", note: "Official API", icon: <PanelsTopLeft className="h-5 w-5" /> },
  { name: "Gmail", note: "Official API", icon: <Mail className="h-5 w-5" /> },
  { name: "Discord", note: "Official API", icon: <Workflow className="h-5 w-5" /> },
  { name: "GitHub", note: "Official API", icon: <GitBranch className="h-5 w-5" /> },
  { name: "Google Docs", note: "Official API", icon: <FileText className="h-5 w-5" /> },
  { name: "Google Sheets", note: "Official API", icon: <Table2 className="h-5 w-5" /> },
]

const proofPoints = [
  { value: "28", label: "posts created in one week" },
  { value: "4", label: "channels running together" },
  { value: "97%", label: "less manual effort" },
]

const comparisonRows = [
  { feature: "Execution", manual: "You remember every post", alpha: "The system remembers your cadence" },
  { feature: "Voice", manual: "You sound rushed", alpha: "You sound consistent" },
  { feature: "Channels", manual: "One by one", alpha: "All at once" },
  { feature: "Growth", manual: "Reactive", alpha: "Compounding" },
]

function SectionTitle({ eyebrow, title, subtitle }: { eyebrow: string; title: ReactNode; subtitle: string }) {
  return (
    <div className="mx-auto max-w-3xl text-center">
      <p className="mb-4 text-[11px] font-black uppercase tracking-[0.36em] text-[#FFD60A]">{eyebrow}</p>
      <h2 className="text-2xl font-black tracking-tight text-white sm:text-3xl lg:text-4xl">{title}</h2>
      <p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-[#8c8c8c] sm:text-base">{subtitle}</p>
    </div>
  )
}

function GlassCard({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`rounded-[1.5rem] border border-[#1f1f1f] bg-[#0a0a0a] p-5 shadow-[0_20px_80px_rgba(0,0,0,0.24)] backdrop-blur-xl sm:p-6 ${className}`}>{children}</div>
}

export default function Page() {
  return (
    <main id="top" className="min-h-screen overflow-x-hidden bg-[#050505] text-white">
      <header className="sticky top-0 z-50 border-b border-[#1f1f1f] bg-[#050505]/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-4 py-4 sm:px-6 lg:px-8">
          <a href="#top" className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.34em] text-white">
            <span className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-[#FFD60A]/25 bg-[#FFD60A] text-sm font-black text-black">⚡</span>
            <span>AlphaTekX</span>
          </a>
          <nav className="hidden items-center gap-7 text-sm font-semibold text-[#8c8c8c] md:flex">
            <a href="#why" className="transition hover:text-white">Why it works</a>
            <a href="#platforms" className="transition hover:text-white">Platforms</a>
            <a href="#pricing" className="transition hover:text-white">Pricing</a>
          </nav>
          <a href="#pricing" className="rounded-[0.85rem] bg-[linear-gradient(90deg,#FFD60A_0%,#FFB800_100%)] px-5 py-2.5 text-sm font-black text-black transition hover:scale-[1.02]">
            Open dashboard
          </a>
        </div>
      </header>

      <section className="px-4 pb-6 pt-8 sm:px-6 lg:px-8 lg:pt-10">
        <div className="mx-auto grid max-w-7xl gap-6 rounded-[2rem] border border-[#1f1f1f] bg-[radial-gradient(circle_at_top_left,_rgba(255,214,10,0.18),transparent_28%),radial-gradient(circle_at_bottom_right,_rgba(168,85,247,0.18),transparent_24%),linear-gradient(135deg,#060606_0%,#0b0b0b_100%)] p-6 sm:p-8 lg:grid-cols-[1.02fr_0.98fr] lg:p-10">
          <div className="flex flex-col justify-between">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full border border-[#1f1f1f] bg-[#0a0a0a] px-3 py-2 text-[10px] font-black uppercase tracking-[0.34em] text-[#FFD60A]">
                <Sparkles className="h-3.5 w-3.5" />
                <span>New: your AI operator is live</span>
              </div>
              <h1 className="mt-6 max-w-3xl text-4xl font-black leading-[0.95] tracking-[-0.03em] text-white sm:text-5xl lg:text-7xl">
                The last social engine you will ever build by hand.
              </h1>
              <p className="mt-6 max-w-xl text-base leading-8 text-[#8c8c8c] sm:text-lg">
                AlphaTekX turns your voice, your documents, and your workflow into a 24/7 publishing machine that still lets you stay in control.
              </p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row">
                <a href="#pricing" className="inline-flex items-center justify-center gap-2 rounded-[0.95rem] bg-[linear-gradient(90deg,#FFD60A_0%,#FFB800_100%)] px-6 py-3.5 text-base font-black text-black transition hover:scale-[1.01]">
                  Launch my second you
                  <ArrowRight className="h-4 w-4" />
                </a>
                <a href="#why" className="inline-flex items-center justify-center rounded-[0.95rem] border border-[#1f1f1f] bg-[#0a0a0a] px-6 py-3.5 text-base font-semibold text-white transition hover:border-[#FFD60A]/40">
                  See how it works
                </a>
              </div>
              <div className="mt-6 flex flex-wrap items-center gap-3 text-sm text-[#8c8c8c]">
                <div className="flex items-center gap-2 rounded-full border border-[#1f1f1f] bg-[#0a0a0a] px-3 py-2">
                  <Lock className="h-4 w-4 text-[#FFD60A]" />
                  <span>Approval stays human</span>
                </div>
                <div className="rounded-full border border-[#1f1f1f] bg-[#0a0a0a] px-3 py-2">No ban risk • Official APIs</div>
              </div>
            </div>
          </div>

          <GlassCard className="border-[#FFD60A]/20 bg-[#0a0a0a]">
            <div className="flex items-center justify-between gap-3">
              <div className="rounded-full border border-[#FFD60A]/25 bg-[#FFD60A]/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.32em] text-[#FFD60A]">
                Live flow
              </div>
              <div className="text-sm text-[#8c8c8c]">4 channels active</div>
            </div>
            <div className="mt-6 rounded-[1.25rem] border border-[#1f1f1f] bg-[#050505] p-4">
              <div className="mb-4 flex items-center justify-between text-[11px] uppercase tracking-[0.3em] text-[#8c8c8c]">
                <span>Growth board</span>
                <span className="text-[#FFD60A]">Running</span>
              </div>
              <div className="space-y-3">
                {proofPoints.map((item) => (
                  <div key={item.label} className="flex items-center justify-between rounded-[1rem] border border-[#1f1f1f] bg-[#0a0a0a] px-4 py-3">
                    <div className="text-sm text-[#8c8c8c]">{item.label}</div>
                    <div className="text-xl font-black text-white">{item.value}</div>
                  </div>
                ))}
              </div>
            </div>
            <div className="mt-4 rounded-[1.25rem] border border-[#1f1f1f] bg-[#050505] p-4 text-sm leading-7 text-[#8c8c8c]">
              “Your audience sees consistency. You keep your time.”
            </div>
          </GlassCard>
        </div>
      </section>

      <section id="why" className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <SectionTitle eyebrow="Why this is different" title="You stop doing the work that should be automated." subtitle="AlphaTekX does not replace your judgment. It removes the repetitive work between your idea and your audience." />
        <div className="mt-8 grid gap-4 lg:grid-cols-3">
          {pillars.map((pillar) => (
            <GlassCard key={pillar.title} className="transition hover:border-[#FFD60A]/35">
              <div className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-[#FFD60A]/10 text-[#FFD60A]">
                <CheckCircle2 className="h-5 w-5" />
              </div>
              <h3 className="mt-4 text-xl font-black text-white">{pillar.title}</h3>
              <p className="mt-3 text-sm leading-7 text-[#8c8c8c]">{pillar.body}</p>
            </GlassCard>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <div className="grid gap-6 lg:grid-cols-[0.38fr_0.62fr]">
          <GlassCard className="border-[#FFD60A]/20 bg-[linear-gradient(135deg,rgba(255,214,10,0.10),rgba(168,85,247,0.12))]">
            <p className="text-[11px] font-black uppercase tracking-[0.32em] text-[#FFD60A]">The engine</p>
            <h3 className="mt-3 text-2xl font-black text-white sm:text-3xl">From input to output, the system keeps moving.</h3>
            <p className="mt-4 text-sm leading-8 text-[#8c8c8c] sm:text-base">
              Your ideas enter once, and the system turns them into consistent posts, replies, and publishing decisions across your channels.
            </p>
            <div className="mt-6 rounded-[1.25rem] border border-[#1f1f1f] bg-[#050505] p-4 text-sm leading-7 text-[#8c8c8c]">
              Your team does not need to chase content. The engine handles the draft, the sequence, and the distribution rhythm.
            </div>
          </GlassCard>

          <div className="space-y-4">
            {steps.map((step) => (
              <GlassCard key={step.title} className="transition hover:border-[#FFD60A]/35">
                <div className="flex items-start gap-3">
                  <div className="mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#FFD60A]/10 text-sm font-black text-[#FFD60A]">{step.title.split('.')[0]}</div>
                  <div>
                    <h4 className="text-lg font-black text-white">{step.title}</h4>
                    <p className="mt-2 text-sm leading-7 text-[#8c8c8c]">{step.body}</p>
                  </div>
                </div>
              </GlassCard>
            ))}
          </div>
        </div>
      </section>

      <section id="platforms" className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <SectionTitle eyebrow="Platforms" title="Built to operate across the places your audience already lives." subtitle="Every channel is connected through one voice model and one approval layer." />
        <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {platforms.map((platform) => (
            <GlassCard key={platform.name} className="transition hover:border-[#FFD60A]/35">
              <div className="flex items-center gap-3 text-[#FFD60A]">
                {platform.icon}
                <h3 className="text-lg font-semibold text-white">{platform.name}</h3>
              </div>
              <p className="mt-3 text-sm leading-7 text-[#8c8c8c]">{platform.note}</p>
            </GlassCard>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <div className="rounded-[1.75rem] border border-[#1f1f1f] bg-[#0a0a0a] p-4 sm:p-6">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#1f1f1f] pb-4">
            <div>
              <p className="text-[11px] font-black uppercase tracking-[0.32em] text-[#FFD60A]">Clear comparison</p>
              <h2 className="mt-2 text-2xl font-black text-white sm:text-3xl">Manual work slows the business down. AlphaTekX compounds it.</h2>
            </div>
            <div className="rounded-full border border-[#FFD60A]/25 bg-[#FFD60A]/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.32em] text-[#FFD60A]">10x better</div>
          </div>
          <div className="mt-4 overflow-x-auto">
            <table className="min-w-full border-collapse text-left text-sm text-[#8c8c8c]">
              <thead>
                <tr className="border-b border-[#1f1f1f] text-[11px] uppercase tracking-[0.3em] text-white">
                  <th className="px-3 py-3 font-black">Area</th>
                  <th className="px-3 py-3 font-black">Manual</th>
                  <th className="px-3 py-3 font-black text-[#FFD60A]">AlphaTekX</th>
                </tr>
              </thead>
              <tbody>
                {comparisonRows.map((row) => (
                  <tr key={row.feature} className="border-b border-[#1f1f1f] last:border-b-0">
                    <td className="px-3 py-3 font-semibold text-white">{row.feature}</td>
                    <td className="px-3 py-3">{row.manual}</td>
                    <td className="px-3 py-3 text-[#FFD60A]">{row.alpha}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section id="pricing" className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <div className="rounded-[1.9rem] border border-[#1f1f1f] bg-[linear-gradient(135deg,rgba(255,214,10,0.16),rgba(168,85,247,0.16))] p-6 sm:p-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
            <div className="max-w-2xl">
              <p className="text-[11px] font-black uppercase tracking-[0.32em] text-[#FFD60A]">Early bird • first 100 locked forever</p>
              <div className="mt-4 flex flex-wrap items-end gap-3">
                <span className="text-5xl font-black text-white sm:text-6xl">$19/mo</span>
                <span className="text-2xl font-semibold text-[#8c8c8c] line-through">$59/mo</span>
                <span className="text-lg font-black text-white">= ₦25,922</span>
              </div>
              <p className="mt-5 text-sm leading-8 text-[#8c8c8c] sm:text-base">
                Includes all six platforms, unlimited AI generation, voice training, Sheets orchestration, and official API access. Your second you stays active while you stay focused.
              </p>
              <a href="#top" className="mt-6 inline-flex items-center justify-center gap-2 rounded-[0.95rem] bg-[linear-gradient(90deg,#FFD60A_0%,#FFB800_100%)] px-6 py-3.5 text-base font-black text-black transition hover:scale-[1.01]">
                Get started now
                <ArrowRight className="h-4 w-4" />
              </a>
            </div>
            <div className="w-full max-w-md rounded-[1.25rem] border border-[#1f1f1f] bg-[#0a0a0a] p-5">
              <div className="space-y-3">
                {[
                  { title: "No ban risk", body: "Official APIs instead of brittle workarounds." },
                  { title: "Approval stays human", body: "You decide what leaves your system." },
                  { title: "Built to scale", body: "One month of content becomes a repeatable engine." },
                ].map((item) => (
                  <div key={item.title} className="rounded-[1rem] border border-[#1f1f1f] bg-[#050505] p-4">
                    <div className="text-sm font-black uppercase tracking-[0.24em] text-white">{item.title}</div>
                    <div className="mt-2 text-sm leading-7 text-[#8c8c8c]">{item.body}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
          <div className="mt-6 flex flex-wrap items-center gap-3 rounded-[1.25rem] border border-[#1f1f1f] bg-[#0a0a0a] px-4 py-4 text-sm text-[#8c8c8c]">
            <div className="flex items-center gap-2 text-[#FFD60A]">
              <ShieldCheck className="h-4 w-4" />
              <span>Trusted by founders who want momentum, not more busywork.</span>
            </div>
            <div className="ml-auto flex items-center gap-2 rounded-full border border-[#1f1f1f] bg-[#050505] px-3 py-2 text-[11px] font-black uppercase tracking-[0.24em] text-white">
              <ChevronRight className="h-4 w-4 text-[#FFD60A]" />
              <span>Built for serious operators</span>
            </div>
          </div>
        </div>
      </section>

      <footer className="border-t border-[#1f1f1f] bg-[#050505] px-4 py-10 sm:px-6 lg:px-8">
        <div className="mx-auto flex max-w-7xl flex-col gap-6 text-center sm:text-left md:flex-row md:items-end md:justify-between">
          <div>
            <p className="text-[11px] font-black uppercase tracking-[0.36em] text-[#FFD60A]">AlphaTekX Technologies</p>
            <p className="mt-3 max-w-xl text-sm leading-7 text-[#8c8c8c]">The operating layer for founders who want consistency, speed, and a stronger public voice without burning their life on publishing.</p>
          </div>
          <div className="text-sm text-[#8c8c8c]">
            <p className="font-mono">alphatekx.name.ng</p>
            <div className="mt-3 flex flex-wrap justify-center gap-4 sm:justify-start">
              {['Privacy', 'Terms', 'Status', 'Contact'].map((link) => (
                <a key={link} href="#top" className="transition hover:text-[#FFD60A]">{link}</a>
              ))}
            </div>
          </div>
        </div>
      </footer>
    </main>
  )
}
